const OBJECTS = {
    OWNERS: "USER_DETAILS",
    FLAT_DETAILS: "FLAT_DETAILS",
    MAINTENANCE_MASTER: "MAINTENANCE_MASTER",
    MAINTENANCE: "MAINTENANCE",
    PAYMENT: "PAYMENT",
    PAYMENT_DETAILS: "PAYMENT_DETAILS",
    EXPENSE_HEAD: "EXPENSE_HEAD",
    EXPENSE: "EXPENSE",
    EXPENSE_ITEMS: "EXPENSE_ITEMS",
    EVENTS: "EVENTS",
    NOTES: "NOTES",
    ACCOUNT: "ACCOUNT",
    ACCOUNT_TRANSACTION: "ACCOUNT_TRANSACTION",
    USER: "USER",
    EMAIL_SETUP: "EMAIL_SETUP",
    USER_ROLE_PERMISSION: "USER_ROLE_PERMISSION",
    PAYMENT_RECEIPT: "PAYMENT_RECEIPT",
    SESSION: "SESSION",
    PROFILE: "PROFILE",
    SETTINGS: "SETTINGS",
    DASHBOARD: "DASHBOARD"
}

const OBJECTS_LABEL = {}
OBJECTS_LABEL[OBJECTS.OWNERS] = "Owners";
OBJECTS_LABEL[OBJECTS.FLAT_DETAILS] = "Flat Details";
OBJECTS_LABEL[OBJECTS.PAYMENT] = "Payment";
OBJECTS_LABEL[OBJECTS.PAYMENT_DETAILS] = "Payment Details";
OBJECTS_LABEL[OBJECTS.MAINTENANCE_MASTER] = "Maintenance Master";
OBJECTS_LABEL[OBJECTS.MAINTENANCE] = "Maintenance";
OBJECTS_LABEL[OBJECTS.EXPENSE_HEAD] = "Expense Head";
OBJECTS_LABEL[OBJECTS.EXPENSE] = "Expenses";
OBJECTS_LABEL[OBJECTS.EXPENSE_ITEMS] = "Expense Items";
OBJECTS_LABEL[OBJECTS.EVENTS] = "Events";
OBJECTS_LABEL[OBJECTS.SETTINGS] = "Settings";
OBJECTS_LABEL[OBJECTS.ACCOUNT] = "Account";
OBJECTS_LABEL[OBJECTS.ACCOUNT_TRANSACTION] = "Account Transaction";
OBJECTS_LABEL[OBJECTS.USER] = "User";
OBJECTS_LABEL[OBJECTS.EMAIL_SETUP] = "Email Setup";
OBJECTS_LABEL[OBJECTS.USER_ROLE_PERMISSION] = "User Role Permission";
OBJECTS_LABEL[OBJECTS.PAYMENT_RECEIPT] = "Payment Receipt";
OBJECTS_LABEL[OBJECTS.SESSION] = "Session";
OBJECTS_LABEL[OBJECTS.PROFILE] = "Profile";




const CHILD_OBJECTS = {};
CHILD_OBJECTS[OBJECTS.PAYMENT] = [ OBJECTS.PAYMENT_DETAILS, OBJECTS.FLAT_DETAILS, ];

const ICONS = {
}
ICONS[OBJECTS.OWNERS] = "fa fa-user";
ICONS[OBJECTS.FLAT_DETAILS] = "fa fa-building";
ICONS[OBJECTS.PAYMENT] = "fa fa-money";
ICONS[OBJECTS.MAINTENANCE_MASTER] = "fa fa-money";
ICONS[OBJECTS.MAINTENANCE] = "fa fa-money";
ICONS[OBJECTS.PAYMENT_DETAILS] = "fa fa-money";
ICONS[OBJECTS.EXPENSE_HEAD] = "fa fa-money";
ICONS[OBJECTS.EXPENSE] = "fa fa-money";
ICONS[OBJECTS.EXPENSE_ITEMS] = "fa fa-money";
ICONS[OBJECTS.EVENTS] = "fa fa-calendar-plus-o";
ICONS[OBJECTS.SETTINGS] = "fa fa-cog";
ICONS[OBJECTS.ACCOUNT] = "fa fa-book";

const FORM_CONSTANTS = {
    VALIDATOR_TYPE_OPTIONAL: "OPTIONAL",
    VALIDATOR_TYPE_REQUIRED: "REQUIRED",
}

const EVENT_TYPES = {
    "ONETIME": "ONETIME",
    // "REGULAR": "REGULAR",
    "SUBEVENT": "SUBEVENT",
}



const MONTHS_FULL_FORM = {
    "1": "January",
    "2": "February",
    "3": "March",
    "4": "April",
    "5": "May",
    "6": "June",
    "7": "July",
    "8": "August",
    "9": "September",
    "10": "October",
    "11": "November",
    "12": "December",
}

const MONTHS_SORT_FORM = {
    "1": "Jan",
    "2": "Feb",
    "3": "Mar",
    "4": "Apr",
    "5": "May",
    "6": "June",
    "7": "July",
    "8": "Aug",
    "9": "Sept",
    "10": "Oct",
    "11": "Nov",
    "12": "Dec",
}

const USER_ROLE = {
    SADMIN: "SADMIN",
    USER: "USER",
    ADMIN: "ADMIN",
    SECRETARY: "SECRETARY",
    ASST_SECRETARY: "ASST-SECRETARY",
    TREASURER: "TREASURER",
    ASST_TREASURER: "ASST-TREASURER"
}

const USER_PERMISSION = {
    CREATE: "CREATE",
	VIEW: "VIEW",
	EDIT: "EDIT",
	DELETE: "DELETE",
}

const AVAILABLE_CRUD_OPERATIONS = {};
AVAILABLE_CRUD_OPERATIONS[OBJECTS.OWNERS] = [USER_PERMISSION.CREATE,USER_PERMISSION.VIEW,USER_PERMISSION.EDIT,USER_PERMISSION.DELETE];
AVAILABLE_CRUD_OPERATIONS[OBJECTS.FLAT_DETAILS] = [USER_PERMISSION.CREATE,USER_PERMISSION.VIEW,USER_PERMISSION.EDIT,USER_PERMISSION.DELETE];
AVAILABLE_CRUD_OPERATIONS[OBJECTS.MAINTENANCE] = [USER_PERMISSION.CREATE,USER_PERMISSION.EDIT,USER_PERMISSION.VIEW,USER_PERMISSION.DELETE];
AVAILABLE_CRUD_OPERATIONS[OBJECTS.EVENTS] = [USER_PERMISSION.CREATE,USER_PERMISSION.VIEW,USER_PERMISSION.EDIT,USER_PERMISSION.DELETE];
AVAILABLE_CRUD_OPERATIONS[OBJECTS.PAYMENT] = [USER_PERMISSION.CREATE,USER_PERMISSION.VIEW,USER_PERMISSION.DELETE];
AVAILABLE_CRUD_OPERATIONS[OBJECTS.PAYMENT_DETAILS] = [USER_PERMISSION.VIEW];
AVAILABLE_CRUD_OPERATIONS[OBJECTS.PAYMENT_RECEIPT] = [USER_PERMISSION.VIEW];
AVAILABLE_CRUD_OPERATIONS[OBJECTS.EXPENSE] = [USER_PERMISSION.CREATE,USER_PERMISSION.VIEW,USER_PERMISSION.EDIT,USER_PERMISSION.DELETE];
AVAILABLE_CRUD_OPERATIONS[OBJECTS.ACCOUNT] = [USER_PERMISSION.EDIT,USER_PERMISSION.VIEW];
AVAILABLE_CRUD_OPERATIONS[OBJECTS.ACCOUNT_TRANSACTION] = [USER_PERMISSION.CREATE,USER_PERMISSION.VIEW,USER_PERMISSION.DELETE];
AVAILABLE_CRUD_OPERATIONS[OBJECTS.EMAIL_SETUP] = [USER_PERMISSION.VIEW];
AVAILABLE_CRUD_OPERATIONS[OBJECTS.USER] = [USER_PERMISSION.CREATE,USER_PERMISSION.VIEW,USER_PERMISSION.EDIT,USER_PERMISSION.DELETE];
AVAILABLE_CRUD_OPERATIONS[OBJECTS.USER_ROLE_PERMISSION] = [USER_PERMISSION.EDIT,USER_PERMISSION.VIEW];
AVAILABLE_CRUD_OPERATIONS[OBJECTS.SESSION] = [USER_PERMISSION.CREATE,USER_PERMISSION.VIEW,USER_PERMISSION.DELETE];



const CONSTANSTS = {
    OBJECTS: OBJECTS,
    OBJECTS_LABEL: OBJECTS_LABEL,
    CHILD_OBJECTS,
    ICONS: ICONS,
    FORM_CONSTANTS: FORM_CONSTANTS,
    MONTHS_SORT_FORM: MONTHS_SORT_FORM,
    MONTHS_FULL_FORM: MONTHS_FULL_FORM,
    EVENT_TYPES,
    USER_ROLE,
    USER_PERMISSION,
    AVAILABLE_CRUD_OPERATIONS
}

export default CONSTANSTS;